### ISSUE TITLE
Wish List (future roadmap)

### ISSUE THREAD

**Issue by hummingly** [hummingly/calendar#3]
Depending how far I come with the core functionalities, I will later work on these here.

The tag system is going to be important because it will shape the GUI of the app. When I have the first point fleshed out, I can work on the GUI itself.
1. - [ ] **Tags**
        - [ ] `tag`s integrated into `Appointment`s
        - [ ] Sorting/Displaying Appointments depending on tag
        - [ ] hide function: tags that are marked as hidden or secret can only show title or just send an anonymous notification
        - [ ] importance level: have certain attributes (e.g. pop-up notification, sound, dispay in calendar)

This needs its own issue because it is going to be complex one way or another (just making it work is going to be difficult).
2. - [ ] **GUI**

The ultimate dream is to make it suitable for daily use (**USEFUL**). Going native is probably is the most reasonable and if it doesn't work, then I will create a small app to sync the calendar files on desktop and mobile which can then be used on both
3. - [ ] **Connecting with mobile devices**
        - [ ] android
        - [ ] iOS
